menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/ashburshui
    StackOverflow: https://ashburshui.github.io/stackoverflow-card
    Travel: https://ashburshui.github.io/travel

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2019
