menu:
  Blog: /
  Archive: /archives/
  Practice: https://ashburshui.github.io/github-card
  Learning: https://ashburshui.github.io/stackoverflow-card
  Travel: https://ashburshui.github.io/travel

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: ashburshui-github-io
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2013
