menu:
  Blog: /
  Archive: /archives/
  Crafts: https://ashburshui.github.io/crafts
  Learning: https://ashburshui.github.io/learning
  Health: https://ashburshui.github.io
  Travel: https://ashburshui.github.io/travel

favicon: /favicon.png
logo: /favicon.png

# Comment
disqus: ashburshui-github-io
duoshuo:

# Analytics
# google-analytics:
ga: UA-136311539-1

# Copyright Infomation
startyear: 2013
