menu:
  Blog: /
  Archive: /archives/
  Craft: /craft/
  Caprice: /caprice/
  Travel: /travel/

favicon: /favicon.png
logo: /favicon.png

# Comment
disqus: ashburshui-github-io
duoshuo:

# Analytics
# google-analytics:
ga: UA-136311539-1

# Copyright Infomation
startyear: 2018
