menu:
    Blog: /
    Archive: /archives/
    Quora: https://www.quora.com/profile/ashburshui
    GitHub: https://github.com/ashburshui
    StackOverflow: https://stackoverflow.com/users/2936650/ashburshui

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2019
